# Use root/example as user/password credentials
version: '3.1'

networks:
  mongo:
    driver: bridge

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - './data:/data'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo

  transformer:
    build: ./code/transformer
    ports:
      - 5000:5000
    networks:
      - mongo

  backend:
    build: ./code/backend
    ports:
      - 5050:5050
    networks:
      - mongo
