# Use root/example as user/password credentials
version: '3.1'

networks:
  mongo:
    driver: bridge

services:

  mongo:
    image: mongo:4.4.10
    restart: always
    volumes:
      - './data:/data'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo

  transformer:
    build: ./code/transformer
    ports:
      - 6000:6000
    networks:
      - mongo

  backend:
    build: ./code/backend
    ports:
      - 5050:5050
    networks:
      - mongo

  frontend:
    build: ./code/pi-react
    ports:
      - 3000:3000
    networks:
      - mongo
